### ISSUE TITLE
Preparação para as entrevistas

### ISSUE THREAD

**Issue by Victor-oss** [ResidenciaTICBrisa/04_PipelineTCU#1]
Teremos duas reuniões com o cliente, a primeira será na próxima quinta (22/06) das 10:00 às 11:00 e a segunda será na terça da semana que vem (27/06) das 09:00 às 11:00. Portanto, o grupo tem de tarefa até essa quarta (21/06):
1. Ler os documentos disponíveis no site do último pipeline de dados feito em 2016 "https://antigo.mctic.gov.br/mctic/opencms/ciencia/SEPED/clima/opcoes_mitigacao/paginas/potenciais_custos_abatimento_setoriais.html"
2. Sugerir perguntas para as entrevistas no doc "https://docs.google.com/document/d/1xB1sd4Ojt9DJsFYcMoiiynjfJU81KiYXc3WnZZf21XU/edit?usp=sharing"
3. Pesquisar as possíveis fontes de dados dos quais poderemos retirar as informações necessárias para o trabalho e deixar suas sugestões como comentário da issue

**Comment by EduardoGurgel** [comment]
#### Balanço do setor energético nacional 2023:
- https://www.epe.gov.br/pt/publicacoes-dados-abertos/publicacoes/balanco-energetico-nacional-2023

**Comment by Victor-oss** [comment]
Existe um relatório periódico do Governo sobre as emissões de gases do efeito estufa e está disponível numa plataforma online. A plataforma se chama SIRENE e fica disponível no link https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene. É bem completo e dá pra baixar os dados no formato excel, só que os dados presentes na plataforma datam de 2016 porque segundo um tratado que o Brasil se comprometeu diz que o período de publicação do relatório é até quatro anos entre a data de submissão ─ que para 4CN foi em 31 de dezembro de 2020 ─ e o último ano inventariado (2016).

**Comment by Victor-oss** [comment]
Outra plataforma online com dados é o Climate Watch https://www.climatewatchdata.org/ghg-emissions?end_year=2019&regions=BRA&sectors=total-including-lucf%2Cbunker-fuels&start_year=1990. Ele possui dados sobre emissões de gases do efeito estufa até 2019 para cada país nos setores agricultura, combustível de navio, energia, processos industriais, uso da terra e florestas além de resíduos. Ele permite salvar os dados em arquivos CSV

**Comment by Victor-oss** [comment]
O Inventário Nacional da Quarta Comunicação Nacional do Brasil à Convenção-Quadro das Nações Unidas sobre Mudança do Clima não só está disponível no SERENA, mas também possui um arquivo pdf no link: https://repositorio.mctic.gov.br/handle/mctic/4782. O setor de Transporte está dentro do Setor de Energia no relatório.
