### ISSUE TITLE
US03 - Visualizar os dados de Balanço de Potência do Brasil e do Mundo

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#100]
# Descrição
Eu como usuário do sistema, gostaria de poder visualizar os dados de Balanço de Potência do Brasil e do Mundo  em formas de gráficos e/ou tabelas

# Tarefas

# Critérios de Aceitação
O que foi concluído até o momento.
- [ ] Critério 1

# Informações Adicionais
## Persona
Primária

**Comment by Victor-oss** [comment]
A parte do Brasil foi feita na issue (#129). Para o mundo, não foi encontrada uma fonte.
