### ISSUE TITLE
Agendamento de Reunião com Coordenadora

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#11]
Levantar dúvidas e pautas para serem discutidas com a professora
## D.O.D
- [ ] Elaborar Perguntas
- [ ] Definir data e hora para a reunião

**Comment by Stain19** [comment]
Solicitar contatos úteis para o projeto

**Comment by Stain19** [comment]
Ideias de Bases de dados

**Comment by caiozim112** [comment]
Setores e Políticas para adição no escopo de análise do projeto

**Comment by Stain19** [comment]
Solicitar Treinamento para curva MAC
