### ISSUE TITLE
US08 - FIltro de Dados atualizados na matriz energética do Brasil

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#110]
# Descrição
Eu como usuário do sistema gostaria de filtrar os dados atualizados da matriz energética do Brasil

# Tarefas

# Critérios de Aceitação

# Informações Adicionais

**Comment by caiozim112** [comment]
@Stain19 Quais seriam os paramêtros do filtro? e quais são os dados atualizados da matriz energética do Brasil?
