### ISSUE TITLE
T11 - Encontrar fonte de dados de Balanço de Potência do Mundo

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#115]
# Descrição
Encontrar fonte de dados de Balanço de Potência do Mundo

# Tarefas

- [ ] Achar a fonte de dados referente ao Balanço de Potência do Mundo

# Critérios de Aceitação

- [ ] Relatar a fonte encontrada no doc
# Informações Adicionais

**Comment by EduardoGurgel** [comment]
## Descrição
Foram adicionados as visualizações das emissões de GEE do Brasil
**OBS: Mundo não foi encontrado uma fonte de dados específica**

![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/22ae9369-bcbf-423a-a6ca-8790eea3dcb0)

## Tipo
- [x] Documentação
