### ISSUE TITLE
T13 - Fazer gráfico/tabela com dados de Balanço de Potência do Mundo no Power BI

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#117]
# Descrição
Faça a descrição da issue.

# Tarefas
Aba responsável por inserir as demandas desta issue.

- [ ] Tarefa 1
- [ ] Tarefa 2

# Critérios de Aceitação
O que foi concluído até o momento.
- [ ] Critério 1

# Informações Adicionais

**Comment by EduardoGurgel** [comment]
**OBS: Mundo não foi encontrado uma fonte de dados específica**
