### ISSUE TITLE
Consumo de Gás Natural no Brasil

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#118]
# Descrição
Pegar dados do consumo de gás natural no Brasil, passar para o banco de dados e depois para o Power BI 

# Tarefas

- [ ] Pegar dados do consumo de gás natural no Brasil e reunir em tabela(s). Sugestões de fontes: BEN
- [ ] Popular o banco de dados com as os arquivos de dados gerados na primeira tarefa seguindo a trilha: Arquivos de dados (.csv, .xlsx) -> Transformação (Visual Studio - SQL Server Integration Services) -> Tabelas SQL server -> Visualização Power BI
- [ ] Fazer gráficos/tabelas no Power BI com os dados

# Critérios de Aceitação
- [ ] Adição das tabelas ao banco
- [ ] Adição dos gráficos no Power BI 
- [ ] Documentação do gráficos no Git Pages do projeto

**Comment by Victor-oss** [comment]
Issue fechada junto com a 129, pois fazendo a 129, fazemos essa issue ao mesmo tempo
