### ISSUE TITLE
Consumo de Gás Natural do Mundo

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#119]
# Descrição
Pegar dados do consumo de gás natural no mundo, passar para o banco de dados e depois para o Power BI 

# Tarefas

- [ ] Encontrar fonte de dados que forneça o consumo de gás natural no mundo
- [ ] Pegar dados do consumo de gás natural no mundo e reunir em tabela(s)
- [ ] Popular o banco de dados com as os arquivos de dados gerados na primeira tarefa seguindo a trilha: Arquivos de dados (.csv, .xlsx) -> Transformação (Visual Studio - SQL Server Integration Services) -> Tabelas SQL server -> Visualização Power BI
- [ ] Fazer gráficos/tabelas no Power BI com os dados

# Critérios de Aceitação
- [ ] Documentação da fonte de dados encontrada na Git Pages do projeto
- [ ] Adição das tabelas ao banco
- [ ] Adição dos gráficos no Power BI 
- [ ] Documentação do gráficos no Git Pages do projeto

**Comment by caiozim112** [comment]
https://www.epe.gov.br/pt/publicacoes-dados-abertos/publicacoes/balanco-energetico-nacional-2023
@Victor-oss no excel existe o consumo final, ele serve?

**Comment by Victor-oss** [comment]
> https://www.epe.gov.br/pt/publicacoes-dados-abertos/publicacoes/balanco-energetico-nacional-2023 @Victor-oss no excel existe o consumo final, ele serve?

Os dados de gás de consumo natural do Brasil nós temos, o que não conseguimos encontrar é no mundo

**Comment by Victor-oss** [comment]
Issue fechada devido ao fato de não encontrarmos nenhuma fonte de dados aberta e gratuita.
