### ISSUE TITLE
Custo de Operação do Sistema Elétrico no Brasil

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#120]
# Descrição
Pegar dados do custo de operação do sistema elétrico no Brasil, passar para o banco de dados e depois para o Power BI 

# Tarefas

- [ ] Encontrar fonte de dados que forneça o custo de operação do sistema elétrico no Brasil. Sugestão de fontes: ONS
- [ ] Pegar dados do custo de operação do sistema elétrico no Brasil e reunir em tabela(s)
- [ ] Popular o banco de dados com as os arquivos de dados gerados na primeira tarefa seguindo a trilha: Arquivos de dados (.csv, .xlsx) -> Transformação (Visual Studio - SQL Server Integration Services) -> Tabelas SQL server -> Visualização Power BI
- [ ] Fazer gráficos/tabelas no Power BI com os dados

# Critérios de Aceitação
- [ ] Documentação da fonte de dados encontrada na Git Pages do projeto
- [ ] Adição das tabelas ao banco
- [ ] Adição dos gráficos no Power BI 
- [ ] Documentação do gráficos no Git Pages do projeto

**Comment by Victor-oss** [comment]
Issue fechada devido ao fato de fonte de dados não permitir o uso de um módulo de web-scrapping em segundo plano para obter os dados e dados aparentam não sofrer atualização desde 2019.
