### ISSUE TITLE
Emissões Equivalentes de CO2 do Mundo

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#122]
# Descrição
Pegar dados do total de emissões equivalentes de CO2 no mundo, passar para o banco de dados e depois para o Power BI 

# Tarefas

- [ ] Pegar dados de emissões equivalentes de CO2 no mundo e reunir em tabela(s). Sugestões de fontes: Irena
- [ ] Popular o banco de dados com as os arquivos de dados gerados na primeira tarefa seguindo a trilha: Arquivos de dados (.csv, .xlsx) -> Transformação (Visual Studio - SQL Server Integration Services) -> Tabelas SQL server -> Visualização Power BI
- [ ] Fazer gráficos/tabelas no Power BI com os dados

# Critérios de Aceitação
- [ ] Adição das tabelas ao banco
- [ ] Adição dos gráficos no Power BI 
- [ ] Documentação do gráficos no Git Pages do projeto

**Comment by EduardoGurgel** [comment]
## Descrição
Foram adicionados as visualizações das emissões de GEE do Brasil
**OBS: Mundo não foi encontrado uma fonte de dados específica**

![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/22ae9369-bcbf-423a-a6ca-8790eea3dcb0)

## Tipo
- [x] Documentação
