### ISSUE TITLE
Emissões Equivalentes de CO2 do Brasil

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#123]
# Descrição
Pegar dados do total de emissões equivalentes de CO2 no Brasil, passar para o banco de dados e depois para o Power BI 

# Tarefas

- [x] Pegar dados de emissões equivalentes de CO2 no Brasil e reunir em tabela(s). Sugestões de fontes: Anuário Estatístico de Energia, Sirene (importante: o anuário só apresenta dados relacionados ao setor de energia, o sirene possui relatórios que possuem dados de todos os setores-chave)
- [x] Popular o banco de dados com as os arquivos de dados gerados na primeira tarefa seguindo a trilha: Arquivos de dados (.csv, .xlsx) -> Transformação (Visual Studio - SQL Server Integration Services) -> Tabelas SQL server -> Visualização Power BI
- [x] Fazer gráficos/tabelas no Power BI com os dados

# Critérios de Aceitação
- [x] Adição das tabelas ao banco
- [x] Adição dos gráficos no Power BI 
- [x] Documentação do gráficos no Git Pages do projeto

**Comment by EduardoGurgel** [comment]
## Emissões GEE Brasil
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/22ae9369-bcbf-423a-a6ca-8790eea3dcb0)
