### ISSUE TITLE
Adicionar dados do BEN ao PowerBI

### ISSUE THREAD

**Issue by Victor-oss** [ResidenciaTICBrisa/04_PipelineTCU#129]
# Descrição
Passar dados do BEN de 1970 até 2022 para o Power BI

# Tarefas
- [x] Fazer script de web-scrapping para os dados do BEN de 1970 até 2022
- [x] Fazer script que reúne os dados de todos os anos em uma única tabela 
- [x] Passar tabela para o banco de dados
- [x] Plotar os dados do BEN no PowerBI

# Critérios de Aceitação
- [x] Scripts de web-scrapping e de organização em tabela
- [x] Tabela na pasta "constants"
- [x] Foto no Git Pages do gráfico/tabela obtido

**Comment by caiozim112** [comment]
@Victor-oss ia acabar de fazer o commit kkk
