### ISSUE TITLE
[Refatorar] Inserir gráfico de área empilhado

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#135]
## Descrição
A pedido do TCU, alguns gráficos necessitavam de uma visualização mais precisa, sendo necessário alterar para gráfico de área empilhado.

## Tarefas
- [x] Verificar quais gráficos necessitam da alteração para área empilhado
- [x] Alterar visualização

**Comment by Stain19** [comment]
@EduardoGurgel poderia descrever melhor esta issue?

**Comment by EduardoGurgel** [comment]
## Descrição
Foram feitas as alterações nos gráficos abaixo.

![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/b67f67df-20ef-4a46-ad55-363120e13f1c)
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/8c00f2a7-f1ec-4435-a5f7-3dae567be9ac)
