### ISSUE TITLE
[Refatorar] Evolução desde 1990 das diferentes fontes de energia.

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#137]
# Descrição
Esta issue foi formulada a partir de uma reunião com o TCU, em que foi citado a necessidade de exibir as informações da evolução das diferentes fontes de tecnologia desde 1990. 

# Tarefas

- [x] Encontrar fonte de dados
- [x] Inserir na base de dados
- [x] Criar visualização no power BI

# Critérios de Aceitação

- [x] Tabela na base de dados
- [x] Na base de dados
- [x] Visualização na Dashboard.

**Comment by Stain19** [comment]
@EduardoGurgel poderia descrever melhor esta issue?

**Comment by EduardoGurgel** [comment]
Descrito!

**Comment by EduardoGurgel** [comment]
## Gráfico adicionado
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/8c8ce1ad-c973-4654-baed-5b52c281755b)
