### ISSUE TITLE
Questionário para reunião com o TCU - 11/07 

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#14]
# Descrição
Adicionar as perguntas que devem ser feitas ao cliente para validar os requisitos do projeto.

# Tarefas

- [x] Inserir perguntas nos comentários desta issue

# Critérios de Aceitação
- [x] Pelo menos uma pergunta

**Comment by EduardoGurgel** [comment]
Quais tipos de funcionalidades seria interessante ter no projeto? Poderia citar algum exemplo de outros projetos como base?

**Comment by caiozim112** [comment]
Existe uma fonte de dados que podemos utiizar?

**Comment by Stain19** [comment]
Seria interessante uma integração do nosso projeto á alguma plataforma já utilizada, ou caberia a elaboração de uma nova?

**Comment by caiozim112** [comment]
Como está essa situação desse problema hoje em dia?

**Comment by EduardoGurgel** [comment]
Levantar dados PNE e BEN, modelar painéis (verificação de planejado/executado; modelar curvas de custo de abatimento).

Estudar fontes, funcionamento e modelagem do Sirene e Sinapse. 

Realizar análise comparativa de potencias de PNE/BEN x Sirene e Sinapse.

Exibir se as emissões cumprem as metas.
