### ISSUE TITLE
[MVP] Colocar tabelas que estão no Sharepoint no banco

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#142]

**Comment by EduardoGurgel** [comment]
A tabela de dados está mais completa do que a tabela do SharePoint
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/90eb9dce-e83d-42e7-b4a2-00e28b09084f)

**Comment by Stain19** [comment]
Falta ainda colocar tabelas relacionadas ao PNE 2050

**Comment by Stain19** [comment]
Faltam as tableas do IRENA e do IEA? @caiozim112

**Comment by Stain19** [comment]
Tabelas PNE 2050 adicionadas

**Comment by Stain19** [comment]
@caiozim112

**Comment by Stain19** [comment]
Quais tabelas foram adicionadas?

**Comment by EduardoGurgel** [comment]
Acredito que não há mais nenhuma tabela pendente, pois ao abrir o painel no PowerBI, não apresenta nenhum erro de referência às tabelas.
