### ISSUE TITLE
[MVP] Implementar versão inicial DataFactory

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#147]
# Descrição
O Azure Data Factory é um serviço que permite orquestrar, agendar e criar fluxos de pipelines. Esta issue tem o objetivo de criar uma versão inicial que será padronizada para todas as outras tabelas.

# Tarefas

- [ ] Implementar versão inicial que será padronizada para as outras tabelas
- [ ] Publicar um tutorial de como utilizar

# Critérios de Aceitação

- [ ] Publicar mídia com a versão inicial

**Comment by EduardoGurgel** [comment]
Versão inicial implementada!

![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/eb4c6468-1228-44cf-a2d9-521094a13fc4)

**Comment by Stain19** [comment]
@EduardoGurgel Mudei algumas issues, como esta, de epico, ou como estava anteriormente, de status. Esta acredito que se encaixaria melhor no status de pipeline.
