### ISSUE TITLE
Elaborar dicionário de dados

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#148]
# Descrição
dicionário de dados é um documento ou repositório que contém metadados detalhados sobre os dados dentro de um sistema de informação.

Aqui tem um exemplo:
https://dadosabertos.mec.gov.br/sisu/item/133-dicionario-de-dados

# Tarefas

- [x] incluir nomes de campos, tipos de dados, descrições, formatos, restrições.
- [x] Descrever brevemente cada tabela e a qual Dashboard está associada.

# Critérios de Aceitação

- [x] Publicar no Gitpages

**Comment by ubrando** [comment]
Documento de mapeamento em: 
https://docs.google.com/document/d/1NTY91Blqaj554qB-K1he2OkkpG3jLp9fnvnYdC-9qxU/edit?usp=sharing

**Comment by Stain19** [comment]
Revisão realizada, foram adicionados alguns comentarios ao doc
Quanto à página do Brasil, a tabela Capacidade_instalada_ger_fóssil_Mundo(GW) não está no banco?

**Comment by EduardoGurgel** [comment]
Dicionário de dados adicionado!
