### ISSUE TITLE
Refatorar Roadmap e Backlog

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#151]

**Comment by EduardoGurgel** [comment]
@Stain19 Poderia descrever quais tarefas necessárias para refatorar o Backlog?

**Comment by EduardoGurgel** [comment]
@Stain19 O Backlog está dividido em grandes tarefas (épicos), e também em pequenas tarefas (histórias de usuário menores).

## Exemplo épicos:
Todos que estão com a tag epic, são os épicos, e possuem um conjunto de tarefas a serem realizados
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/c06bf415-459f-4a0e-a99a-57473de5a9cf)

## Conjunto de tarefas
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/b6bcf093-2696-4b48-92ce-4cb4d1a76397)

**Comment by Stain19** [comment]
A refatoração do Projects foi concluída.
Ficou pendente apenas a definição do roadmap.

**Comment by Stain19** [comment]
@EduardoGurgel Poderia revisar o Projects e conferir se está ok?
