### ISSUE TITLE
[Refatorar] Agrupar Mundo em uma única página

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#158]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/666f3a6f-39a2-47a5-8b69-099b37ff797c)
## Tarefas
- [x] Agrupar as duas páginas acima em uma única página
- [x] Inserir um seletor ou referência para cada uma

**Comment by ubrando** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/52638444/ff7c2af5-aa79-44c2-a00c-cba3cec685ee)

Implementado!
