### ISSUE TITLE
[Refatorar] Agrupar Brasil em uma única página

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#159]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/8fccaa19-16a1-4716-864c-b04eb8f55d48)

## Tarefas
- [x] Agrupar as três páginas acima em uma única página
- [x] Inserir um seletor ou referência para cada uma

**Comment by ubrando** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/52638444/26925ce5-55c8-4047-9aab-2e0e3342f2ad)

**Comment by EduardoGurgel** [comment]
Finalizada!
