### ISSUE TITLE
Estudar fontes, funcionamento e modelagem do Sirene e Sinapse. 

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#16]
# Tarefas
Aba responsável por inserir as demandas desta issue.

- [x] Estudar fontes
- [x] funcionamento e modelagem do Sirene e Sinapse

**Comment by Stain19** [comment]
Haveria algum relatório de estudo das fontes, funcionamento e modelagem do SIRENE e do SINAPSE?
Caso haja, por favor, referêncie nesta issue.

**Comment by EduardoGurgel** [comment]
https://residenciaticbrisa.github.io/04_PipelineTCU/analise/projetos_similares/
