### ISSUE TITLE
Estudo dos Dados de Subsídio para Transformação energética

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#167]
# Descrição
O TCU enviou um documento contendo todas as fontes relacionada aos Dados de Subsídio para Transformação Energética, precisamos analizá-las para entender como podemos utilizá-las no nosso projeto.

# Tarefas
- [x] Análise dos dados das fontes enviadas pelo TCU
- [ ] Documento com mapeamento dos dados

# Critérios de Aceitação
O que foi concluído até o momento.
- [ ] Documento de mapeamento.

# Informações Adicionais

**Comment by ubrando** [comment]
O estudo foi realizado e o mapeamento dos dados estão em:
https://docs.google.com/document/d/1E7u__X45Ay0Sb_3zERSt8jF_4UJwsrXQRLHIDaLMa8Y/edit?usp=sharing
