### ISSUE TITLE
[Refatorar] Matriz energética Brasil e Mundo são iguais

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#169]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/a0abf39c-fc17-4680-8eed-1843532bfce3)

## Descrição
Acabei de verificar algumas visualizações e vi que a Matriz Brasil e Mundo são iguais.

## Tarefas
- [x] Corrigir a visualização Brasil x Mundo

**Comment by ubrando** [comment]
Corrigido
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/52638444/198ffcbd-2e09-49c8-b247-d74db03bbfdb)
