### ISSUE TITLE
Realizar análise comparativa de potencias de PNE/BEN x Sirene e Sinapse.

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#17]
# Tarefas

- [x] Realizar análise comparativa de potencias de PNE/BEN
- [x] Realizar análise comparativa de potencias de Sirene e Sinapse.

**Comment by Stain19** [comment]
Existe algum relatório referente a esta análise?
Se sim, por favor, referêncie nesta issue.
