### ISSUE TITLE
[Refatorar] Corrigir paleta de cor de todos os gráficos

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#179]
# Descrição
Foi solicitado pelo cliente a mudança das cores dos gráficos na dashboard, tendo em vista que existem cores que são muito próximas uma da outra, possuindo pouco contraste, o que acarreta em uma dificuldade na visualização dos dados.

# Tarefas
- [x] Escolher uma paleta de cores em que cada cor contrasta a outra próxima
- [x] Modificar as cores de todos os gráficos

# Critérios de Aceitação
- [x] Cores condizentes com o dashboard (do ponto de design)
- [x] Fácil visualização, o usuário deve poder diferenciar cada variável sem dificuldade por conta das cores
# Informações Adicionais
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/66c862a0-3742-4073-89c0-21242ec99fd8)

**Comment by caiozim112** [comment]
Usei essas cores para as fontes:
Hidro:#0072B2
Bio:#009E73
GD:##ED99B7
Gas Natural:#E6E6E6
Eolica:#808080
Pot. COmpl:#9B0065
Nuclear:#AEFF00
Outros:#AE00FF
Carvão:#805600
Oleo C:#2E0001
Solar:#E13102
para Colunas Unicas:
#0D6ABF

**Comment by caiozim112** [comment]
Realizado!
