### ISSUE TITLE
[Refatorar] Converter gráficos de Empregabilidade para Stacked área chart

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#180]
# Descrição
Foi Solicitado pelo cliente a mudança dos gráficos dispostos na página de empregabilidade para um gráfico do tipo do Stacked Area Chart.

# Tarefas

- [x] Alterar o tipo do gráfico para o solicitado pelo cliente

# Critérios de Aceitação
- [x] Gráfico de acordo com o solicitado pelo cliente.

# Informações Adicionais
_Esse tipo de dado não ficaria melhor num “stacked área chart”?_
_Talvez até em dois, sendo um em valores absolutos e outros em percentual?_
-- João Paulo.

**Stacked Area Chart:**
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/5422a134-179b-4a2e-8df3-a6aa7d0d342a)

**Comment by ubrando** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/52638444/a3d05904-5cf5-401f-81e2-8f1f45a9f3f5)
