### ISSUE TITLE
[Refatorar] Página Geração de Energia

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#181]
# Descrição
Cliente relatou que falta especificar o tipo da unidade do dado mostrado nos gráficos da pagina de geração de energia e sugeriu a mudança dos gráficos para os do tipo Stacked Area Chart.

# Tarefas
- [x] Adicionar unidade dos dados
- [x] Alterar os gráficos da pagina para Stacked Area Chart.

# Critérios de Aceitação 
- [ ] Gráficos Stacked Area Chart
- [ ] Unidade dos dados explicita

# Informações Adicionais
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/038a9e65-85ac-4fa9-9ea9-d0b7ac8bc790)

**Comment by caiozim112** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/83408899/86aa467a-e8c4-42f0-8374-ebbeb4543fb1)

**Comment by caiozim112** [comment]
@ubrando
