### ISSUE TITLE
[Refatorar] Matriz energética fonte de dados, filtrar por país e seletor e aumentar

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#182]
# Descrição
O cliente solicitou algumas mudanças dentre elas a fonte dos dados, a adição de uma função para poder filtrar o gráfico de matriz energética mundo por pais por meio de um seletor, além de uma sugestão especifica para união de dois gráficos.
# Tarefas
- [x] Adicionar a fonte de dados de cada gráfico
- [x] Caso possível, fazer um único gráfico onde é possível filtrar para qual pais deve ser exibido os dados.
- [x] Separar os dados de Matriz energética do mundo por pais
- [x] Adicionar o filtro para o gráfico
- [x] Remover o terceiro gráfico
- [x] Adicionar uma caixa de seleção de fontes
- [x] Mudar a cor de seleção do filtro
# Critérios de Aceitação
- [x] Gráficos unificados
- [x] Fonte dos Dados explicita
- [x] Filtro para seleção de países
- [x] Caixa de seleção de fontes

# Informações Adicionais
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/00b62ca3-b526-4b03-8a01-aef82bb64bbe)
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/83408899/23b08f2b-4370-4d45-bf53-2f4fd29061c4)

**Comment by caiozim112** [comment]
Não é possível remover o terceiro gráfico, umas das razões é que a Matriz energética e a participação de Renováveis componhem os mesmos dados mas de forma diferente, enquando a participação de Renováveis é separado por éolica,Hidro e Solar não acontece o mesmo na matriz energética como éolica,solar e etc que ficam juntos.

**Comment by caiozim112** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/83408899/9cc6d29c-c13c-42fa-805c-a2852c74b56e)

**Comment by Stain19** [comment]
@caiozim112 quanto a opção de fazer um seletor de países para estes gráficos, estou fazendo os scripts de extração para que possamos ter todos os dados necessários, você acha que seria possível fazer esta modificação?
Sabe se os dados de participação de renováveis são dispostos pelo IEA e, se sim, eles possuem os dados por países?

**Comment by caiozim112** [comment]
@Stain19 conseguimos filtrar por países
Os dados de participação estão diponíveis no IEA:
https://www.iea.org/data-and-statistics/data-tools/energy-statistics-data-browser?country=WORLD&fuel=Energy%20supply&indicator=TESbySource
