### ISSUE TITLE
[Refatorar] Capacidade instalada - Retirar informações redundantes, Colocar separadores de milhar

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#184]
## Tarefas
- [x] Retirar informações redundantes
- [x] Colocar separadores de milhar
- [x] Retirar vários seletores distintos

**Comment by caiozim112** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/83408899/988c0a9f-ff18-40f9-ba08-d76bd2047b16)
