### ISSUE TITLE
Elaborar documento post-mortem do projeto

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#193]
# Descrição
O post-mortem é uma análise retrospectiva que ocorre após a conclusão de um projeto. Avaliar um projeto depois do fim permite entender quais foram os processos por trás das partes bem sucedidas, assim como aquelas que representam uma área de melhoria criativa e profissional. É importante olhar para o próprio trabalho e avaliá-lo com honestidade

# Tarefas
Cada membro deve realizar
- [ ] Uma retrospectiva autocrítica de participação do projeto
- [ ] Descrever suas contribuições para o projeto
- [ ] O que aprendeu
- [ ] O que deveria ter feito de melhor
- [ ] Quais foram suas fraquezas e como aprimorá-las.

# Critérios de Aceitação
Todos os membros devem:
- [ ] Comentar nesta issue
- [ ] Realizar a análise e documentar no gitpages

**Comment by Stain19** [comment]
Minha parte foi adicionada 👍🏼
