### ISSUE TITLE
[Refatorar] Adicionar nome das páginas nos botões

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#204]
# Descrição
Colocar o nome nos hovers que aparecem ao passar o mouse nos botões da home

# Tarefas

- [x] PNE 2050
- [x] Matriz Energética
- [x] Empregabilidade
- [x] Geração de Energia
- [x] Balanço de Energia
- [x] Consumo Total
- [x] Balanço Nacional
- [x] Brasil
- [x] Mundo
- [x] Geração Período Médio

# Critérios de Aceitação
O que foi concluído até o momento.
- [ ] Em todas as páginas da dashboard os botões do menu lateral estão com os hovers nomeados.

# Informações Adicionais

![Image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/974647fe-a38b-4d64-9e14-cfa630924507)

**Comment by caiozim112** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/83408899/6d446647-8959-483e-ba4b-e413d1e66d20)
Feito!
