### ISSUE TITLE
[Refatorar] Refinar design da Dashboard

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#206]
# Descrição
A dashboard está demandando alguns refinamentos quanto ao seu design.

# Tarefas
- [x] Reorganizar componentes da página Balanço de Potência
- [x] Mudar a Cor do botão da página atual no menu lateral
- [x] Reorganizar aba lateral da página Mundo
- [x] Arrumar o texto do Botão de Balanço de Potência no menu principal

# Critérios de Aceitação
- [x] Todas as tarefas cumpridas

# Informações Adicionais

![Image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/7df38e01-48b9-4f72-89e4-f660d6f52658)

![Image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/6278f543-9617-4ee8-b588-e37d21567f3e)

![Image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/c5284ef1-97a6-4dc2-928d-b765edd0fdee)

![Image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/98167728/917b7825-b70f-4229-91da-ecbf6ecc2514)

**Comment by ubrando** [comment]
Todas as alterações solicitadas foram atendidas
