### ISSUE TITLE
Curvas MACC Sinapse

### ISSUE THREAD

**Issue by Victor-oss** [ResidenciaTICBrisa/04_PipelineTCU#23]
# Descrição
Pegar todas as curvas MACCs disponibilizadas no SInapse das políticas relacionadas a energia e reuni-lás em um único gráfico.

# Tarefas
- [ ] Fazer web-scraping das curvas MACCs do Sinapse de políticas públicas relacionadas ao setor de energia
- [ ] Plotar todas as curvas em um único gráfico

# Critérios de Aceitação
- [ ] Gráfico com todas as curvas MACCs do Sinapse de políticas energéticas com legenda

**Comment by EduardoGurgel** [comment]
Realizei a seguinte análise do projeto SINAPSE.
https://residenciaticbrisa.github.io/04_PipelineTCU/analise/projetos_similares/
