### ISSUE TITLE
Analisar o IRENA mais atualizado

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#26]
## Descrição
Essa análise torna-se necessária para captar quais dados, informações podem ser utilizados para elaboração da ferramenta para tomada de decisão do TCU em relação a adoção de tecnologias e/ou políticas públicas que contribuem para transição energética com base em medidas sustentáveis.
### Dados
- Como estes dados são obtidos?
- Como estes dados se relacionam?
- Qual a utilidade destes dados para o TCU?
### Informações
- Qual a utilidade destas informações para o TCU?
- Como eles se relacionam?
- Quais dados são necessários para o levantamento destas informações?
### Métodos
- Caso necessário, qual cálculo é utilizado para se obter  uma determinada informação/dado?

## D.O.D
- [x] Listar dados e informações obtidos, suas relações, resumos, cálculos, etc.
- [x] Reunir-se com os outros integrates do grupo e detalhar o que foi estudado.

**Comment by Victor-oss** [comment]
Criação de documento com resumo das informações do IRENA e disponibilizado no link https://docs.google.com/document/d/1BDideO2hrpJMXm4Z-1xcoOCk8xXdPfX8DGtNJO09rq4/edit?usp=sharing
