### ISSUE TITLE
PowerBi- Participação por setor na matriz energética brasileira

### ISSUE THREAD

**Issue by caiozim112** [ResidenciaTICBrisa/04_PipelineTCU#32]
# Descrição
Criar Dashboards no PowerBi relacionado ao tema de Participação por setor na matriz energética brasileira

# Tarefas

- [x] Referenciar as fontes citadas Github Pages
- [ ] Postar o link do PowerBi
- [x] Colocar a captura da imagem no Github Pages

**Comment by Stain19** [comment]
Finalizado
