### ISSUE TITLE
PowerBi- Custo de implementação de cada setor/tecnologia

### ISSUE THREAD

**Issue by caiozim112** [ResidenciaTICBrisa/04_PipelineTCU#34]
# Descrição
Criar Dashboards no PowerBi relacionado ao tema de Custo de implementação de cada setor/tecnologia

# Tarefas

- [x] Referenciar as fontes citadas no Github Pages
- [x] Postar o link do PowerBi
- [x] Colocar a captura da imagem no Github Pages

**Comment by EduardoGurgel** [comment]
Finalizado!
![PainelTCU](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/0718b238-2f3a-4c37-994c-91905d5549a0)
