### ISSUE TITLE
Disponibilizar documentação para o TCU

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#48]
# Descrição
- [ ] Disponibilizar documentação no SharePoint
- [ ] Verificar se o Sharepoint possui suporte para markdown
- [ ] Possibilitar a atualização do repositório com a documentação do TCU

**Comment by caiozim112** [comment]
@EduardoGurgel Se ao criar uma documentação local do sharepoint, vamos precisar recriar tudo do zero para o sharepoint do TCU? porque caso precise é melhor deixar a documentação no Github Pages e depois migrar para o Sharepoint do TCU.
Agora: Github Pages->Sharepoint local->Sharepoint TCU
Proposto:Github Pages ->Sharepoint TCU

**Comment by EduardoGurgel** [comment]
@caiozim112 Vamos disponibilizar o documento em markdown

**Comment by caiozim112** [comment]
Com a conversa que tivemos com o TCU, seria melhor disponibilizar o proprio github pages como Documentação.
