### ISSUE TITLE
Implementar modelo de arquitetura do Stream de dados

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#49]
# Descrição

- [ ] **Definir o escopo da extração de dados.**
Determinar os dados que iremos extrair, transformar e visualizar. Certificar-se de ter uma compreensão clara dos requisitos.

- [ ] **Criar um Plano:**
Elabore um plano detalhado que abranja a extração de dados, a transformação, o carregamento no Power BI e a visualização.

- [ ] **Configuração Inicial:**
Certificar-se de que você tenha as ferramentas necessárias instaladas, incluindo o Power Automate, o Power BI, Python e um banco de dados SQL, se necessário.

- [ ] **Configuração do Banco de Dados SQL:**
Configure seu banco de dados SQL com as tabelas e colunas necessárias para armazenar os dados extraídos.

- [ ] **Desenvolvimento do Script Python de extração:**
Escreva o script Python que realiza a extração, transformação e carregamento (ETL) dos dados. Isso pode incluir a conexão com o banco de dados, manipulação de dados e transformações específicas.

- [ ] **Criar um Fluxo no Power Automate:**
Criar um fluxo no Power Automate para automatizar o processo. O fluxo pode ser acionado por um start, como um horário específico, um evento ou uma ação.

- [ ] **Adicionar Ações ao Fluxo:**
No fluxo, adicione ações que executam etapas específicas, como executar o script Python, extrair dados do banco de dados ou executar outras ações necessárias.

- [ ] **Execute o Script Python:**
Configure uma ação no fluxo para executar o script Python. Isso pode ser feito usando a ação "Executar Script" ou "Executar Programa" (dependendo da configuração do Power Automate).

- [ ] **Capture Resultados do Script:**
Configure a ação para capturar os resultados do script Python, como um arquivo **CSV** ou JSON gerado pelo script.

- [ ] **Carregamento no Power BI:**
Configurar uma ação no fluxo para carregar o arquivo de resultados no Power BI. Isso pode ser feito usando a ação "Carregar Arquivo" ou outra ação relevante.

- [ ] **Desenvolva os Relatórios no Power BI:**
No Power BI, desenvolva os relatórios e painéis que exibirão os dados. Conecte-se ao arquivo carregado e crie visualizações que atendam aos requisitos do projeto.

- [ ] **Agende a Atualização:**
Configure agendamentos para que o fluxo seja executado automaticamente em intervalos regulares, mantendo os dados atualizados no Power BI.

- [ ] **Testar e Validar:**
Testar todo o processo para garantir que os dados são extraídos corretamente, o script Python é executado sem erros, os dados são carregados no Power BI e as visualizações estão corretas.

- [ ] **Ajustes e Otimizações:**
Faça ajustes e otimizações conforme necessário para melhorar o desempenho, a precisão e a eficiência do fluxo.

# Anterior
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/bf95d91c-ad44-4761-8780-beb4701e3e3d)

# Atual
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/83e6dfb0-c29a-482d-8e76-248a335dab3b)

**Comment by caiozim112** [comment]
@caiozim112 Parte de extração com Automate-Fluxos

**Comment by caiozim112** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/83408899/ace8ed80-c99a-450b-bb6e-1237627262e7)
nova arquitetura criada.

**Comment by EduardoGurgel** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/cb17934a-e8f9-4a98-a4a3-7fe0921b780c)
