### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#62]
# Descrição
Casos de uso são uma técnica fundamental na engenharia de requisitos e no desenvolvimento de software. Eles descrevem como os usuários interagem com um sistema em cenários específicos, capturando os requisitos funcionais e comportamentais do sistema.
 
# Tarefas

- [ ] Identificação dos Atores
- [ ] Identificação dos Cenários
- [ ] Detalhamento dos Cenários

# Critérios de Aceitação

- [ ] Documentar no gitpages

**Comment by EduardoGurgel** [comment]
@Stain19 Teria como começar essa?

**Comment by Stain19** [comment]
@EduardoGurgel posso tentar, mas essa fase de elicitação de requisitos nós não já passamos?

**Comment by EduardoGurgel** [comment]
Já passamos, mas acredito que é necessário documentar.

**Comment by EduardoGurgel** [comment]
![image](https://github.com/ResidenciaTICBrisa/04_PipelineTCU/assets/51385738/b36e702f-d570-4310-badd-439c53129055)
