### ISSUE TITLE
Cenários

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#63]
# Descrição
São descrições detalhadas de como o sistema ou software será usado em situações específicas do mundo real. Eles fornecem um contexto para entender como os usuários interagem com o sistema e como ele responde a diferentes ações ou eventos. Cada cenário descreve uma sequência de passos ou interações que ocorrem entre o usuário e o sistema, juntamente com as respostas esperadas do sistema.

# Tarefas

- [ ] Cenário 01 - Visualizar Balanço Energético
- [ ] Cenário 02 - Consultar Fontes e Tecnologias
- [ ] Cenário 03 - Inserir possível valor de investimento por tecnologia
- [ ] Cenário 04 - Simular emissões

# Critérios de Aceitação

- [ ] Documentar no gitpages

**Comment by caiozim112** [comment]
#114
