### ISSUE TITLE
Léxico

### ISSUE THREAD

**Issue by EduardoGurgel** [ResidenciaTICBrisa/04_PipelineTCU#64]
# Descrição
O léxico refere-se a um conjunto de termos e vocabulário específico utilizados para descrever e definir os requisitos de um sistema ou software.
 
# Tarefas

- [x] Criar tabela
- [x] Criar classificação
- [x] Criar sinônimo

# Critérios de Aceitação

- [x] Documentado no gitpages

**Comment by caiozim112** [comment]
wip
