### ISSUE TITLE
T10 - Fazer Gráfico/Tabela com dados de Geração Período Médio do Brasil no PowerBI

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#97]
# Descrição
Deve ser feito uma tabela e/ou um gráfico com os dados de Geração Período Médio do Brasil no PowerBI, atendendo ao solicitado na US02

# Tarefas

- [ ] Criar gráfico e/ou tabela no PowerBI
- [ ] Criar documentação relativa a Tabela criada

# Critérios de Aceitação
- [ ] Tabela/Gráfico disponível no SharePoint
- [ ] Tabela/Gráfico  documentada(o)

**Comment by Victor-oss** [comment]
Issue fechada devido ao fato de fonte de dados não permitir o uso de um módulo de web-scrapping em segundo plano para obter os dados.
