### ISSUE TITLE
US02 - Visualizar os dados de Geração Período Médio do Brasil e do Mundo

### ISSUE THREAD

**Issue by Stain19** [ResidenciaTICBrisa/04_PipelineTCU#99]
## Descrição
Eu como usuário do sistema, gostaria de poder visualizar os dados de Geração Período Médio do Brasil e do Mundo em formas de gráficos e/ou tabelas.

**Comment by caiozim112** [comment]
@Victor-oss A geração do mundo já temos ou ainda falta pesquisa? a geração  do Brasil podemos colocar tanto das fontes do ben como da ONS

**Comment by Victor-oss** [comment]
Não encontrada nenhuma fonte que fornece a Geração no Período Médio no Brasil ou no Mundo.
